#!/bin/bash
# Monitoring Setup Guide for Lapak

echo "📊 Monitoring Setup - $(date)"
echo "============================="
echo

echo "1. Cloudflare Pages Analytics"
echo "   ✅ Automatically enabled for all CF Pages projects"
echo "   Location: https://dash.cloudflare.com/09dabe15db11e2f59e97c9807c18cf73/pages/view/lapak-marketing/analytics"
echo "   Metrics: Page views, bandwidth, requests, errors, geography"
echo ""

echo "2. Cloudflare Workers Analytics"
echo "   When deployed, enable in Workers dashboard:"
echo "   Location: https://dash.cloudflare.com/09dabe15db11e2f59e97c9807c18cf73/workers"
echo "   Metrics: Invocations, errors, CPU time, wall time, KV/R2 usage"
echo ""

echo "3. Supabase Monitoring"
echo "   Project: emopndwniprbmkwxqnrz"
echo "   Location: https://supabase.com/dashboard/project/emopndwniprbmkwxqnrz/logs"
echo "   Metrics: Query performance, auth events, storage usage, edge functions"
echo ""

echo "4. Error Tracking"
echo "   Option 1: Cloudflare Workers logs (free, built-in)"
echo "   Option 2: Sentry (paid, better UX)"
echo "   Option 3: Logflare (open source, self-hosted)"
echo ""

echo "5. Uptime Monitoring"
echo "   Free options:"
echo "   • Better Uptime: https://betteruptime.com/"
echo "   • UptimeRobot: https://uptimerobot.com/"
echo "   • Cron-job.org: https://cron-job.org/"
echo ""

echo "6. Alerting Configuration"
echo ""
echo "Critical alerts (SMS + email):"
echo "   • Site down (HTTP 5xx or timeout)"
echo "   • Error rate > 5%"
echo "   • API response time > 3s (p95)"
echo ""
echo "Warning alerts (email only):"
echo "   • Error rate > 1%"
echo "   • API response time > 1s (p95)"
echo "   • Storage usage > 80%"
echo ""

echo "7. Recommended Monitoring Setup"
echo ""
echo "Step 1: Configure CF Pages analytics (already enabled)"
echo "   - Visit: https://dash.cloudflare.com/09dabe15db11e2f59e97c9807c18cf73/pages/view/lapak-marketing/analytics"
echo "   - Review metrics: Page views, top pages, geography"
echo ""
echo "Step 2: Set up uptime monitor (after full platform launch)"
echo "   - Create monitor for: https://b067f355.lapak-marketing.pages.dev"
echo "   - Check every 1 minute"
echo "   - Alert on 2 consecutive failures"
echo ""
echo "Step 3: Enable Supabase logs (when API deployed)"
echo "   - Visit: https://supabase.com/dashboard/project/emopndwniprbmkwxqnrz/logs"
echo "   - Filter by: auth, storage, edge_functions"
echo "   - Set up alerts for errors"
echo ""
echo "Step 4: Configure Workers analytics (when workers deployed)"
echo "   - Visit: https://dash.cloudflare.com/09dabe15db11e2f59e97c9807c18cf73/workers"
echo "   - Enable: Real-time logs, metrics"
echo "   - Set up alerts for errors"
echo ""

echo "8. Key Metrics to Track"
echo ""
echo "Marketing Site:"
echo "   • Page views per day"
echo "   • Unique visitors"
echo "   • Bounce rate"
echo "   • Top pages"
echo "   • Geography"
echo ""
echo "API (when deployed):"
echo "   • Requests per minute"
echo "   • Response time (p50, p95, p99)"
echo "   • Error rate"
echo "   • CPU usage"
echo "   • KV/R2 operations"
echo ""
echo "Database (when deployed):"
echo "   • Active connections"
echo "   • Query performance (slow queries)"
echo "   • Storage usage"
echo "   • Auth events (signups, logins)"
echo ""

echo "✅ Next Steps"
echo ""
echo "1. Visit CF Pages analytics dashboard"
echo "2. Review current metrics for marketing site"
echo "3. Set up uptime monitor (Better Uptime recommended)"
echo "4. Configure alerting endpoints"
echo ""